/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp Pavilion
 */
public class addNew_User extends javax.swing.JPanel {
    Connection conn=null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form addNew_User
     */
    public addNew_User() {
        initComponents();
        conn = DBconnect.connect();
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uaddbtn = new javax.swing.JButton();
        unamebox = new javax.swing.JTextField();
        typebox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        upassbox = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uaddbtn.setBackground(new java.awt.Color(204, 255, 255));
        uaddbtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        uaddbtn.setText("Add users");
        uaddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaddbtnActionPerformed(evt);
            }
        });
        add(uaddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 160, 50));

        unamebox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(unamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 240, 40));

        typebox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        typebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee", "HR" }));
        add(typebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 240, 40));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel3.setText("ADD A NEW USER");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 480, 88));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel7.setText("User Type");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, 35));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel4.setText("Password      ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 36));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel6.setText("Username ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 35));
        add(upassbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1340, 1020));
    }// </editor-fold>//GEN-END:initComponents

    private void uaddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uaddbtnActionPerformed
        String uname= unamebox.getText();
        String utype= typebox.getSelectedItem().toString();
        String upassword= String.valueOf(upassbox.getPassword());
        
        
        try{
            String q = "INSERT INTO users (username, password, user_type) values (?,?,?)";
            pst = conn.prepareStatement(q);

            pst.setString(1,uname);
            pst.setString(2,utype);
            pst.setString(3,upassword);
           
 
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Your New User Login Inserted Successfully!!");
            clearFields();
          
        } catch(SQLException e){
            
        }
        
        

    }//GEN-LAST:event_uaddbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> typebox;
    private javax.swing.JButton uaddbtn;
    private javax.swing.JTextField unamebox;
    private javax.swing.JPasswordField upassbox;
    // End of variables declaration//GEN-END:variables



    private void clearFields() {
       unamebox.setText(null);
        typebox.setSelectedItem(null);

}
}
