/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

import javax.swing.JOptionPane;

/**
 *
 * @author Kaveesha
 */
public class AdminmainInterface extends javax.swing.JFrame {

    /**
     * Creates new form maininterface
     */
    public AdminmainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        change_password = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        salarybtn = new javax.swing.JButton();
        employeebtn = new javax.swing.JButton();
        machinebtn = new javax.swing.JButton();
        black = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        restore1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("backup");

        jButton2.setText("backup");

        change_password.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        change_password.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salarybtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        salarybtn.setForeground(new java.awt.Color(153, 0, 0));
        salarybtn.setText("salary ");
        salarybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarybtnActionPerformed(evt);
            }
        });
        getContentPane().add(salarybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 180, 49));

        employeebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        employeebtn.setForeground(new java.awt.Color(153, 0, 0));
        employeebtn.setText("Employee management");
        employeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeebtnActionPerformed(evt);
            }
        });
        getContentPane().add(employeebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 260, 49));

        machinebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        machinebtn.setForeground(new java.awt.Color(153, 0, 0));
        machinebtn.setText("User Management");
        machinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(machinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 49));

        black.setBackground(new java.awt.Color(153, 153, 255));
        black.setForeground(new java.awt.Color(0, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpeg"))); // NOI18N

        black.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout blackLayout = new javax.swing.GroupLayout(black);
        black.setLayout(blackLayout);
        blackLayout.setHorizontalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, Short.MAX_VALUE)
        );
        blackLayout.setVerticalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blackLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 640));

        restore1.setText("Exit");
        restore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restore1ActionPerformed(evt);
            }
        });
        getContentPane().add(restore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coverrrrr.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1390, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salarybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarybtnActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        salary c=new salary();
        black.add(c).setVisible(true);
       
        
    }//GEN-LAST:event_salarybtnActionPerformed

    private void employeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeebtnActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        NewemployeeDetails c=new NewemployeeDetails();
        black.add(c).setVisible(true);
    }//GEN-LAST:event_employeebtnActionPerformed

    private void machinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machinebtnActionPerformed
        
         String x = User_Management_1.x;
        
        try{
            
            if(x == null){
                User_Management_1 e = new User_Management_1();
            black.add(e);
            black.moveToFront(e);
            e.setSize(black.getWidth(), black.getHeight());
            e.setLocation(0, 0);
            }else{
                JOptionPane.showMessageDialog(null, "Please close the Existing Window.");
            }
            
            
        }catch(Exception e1){
            e1.printStackTrace();
        }
        
        
    }//GEN-LAST:event_machinebtnActionPerformed

    private void restore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restore1ActionPerformed
        UserLogin admin = new UserLogin();
        admin.setVisible(true);
    }//GEN-LAST:event_restore1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminmainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminmainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminmainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminmainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminmainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane black;
    private javax.swing.JDialog change_password;
    private javax.swing.JButton employeebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton machinebtn;
    private javax.swing.JButton restore1;
    private javax.swing.JButton salarybtn;
    // End of variables declaration//GEN-END:variables
}
