/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hp Pavilion
 */
public class Customermachine extends javax.swing.JInternalFrame {
        Connection conn=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form Customermachine
     */
    public Customermachine() {
        initComponents();
        conn = DBconnect.connect();
        tableLoad();
         BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listner : basicInternalFrameUI.getNorthPane().getMouseListeners()){
            basicInternalFrameUI.getNorthPane().removeMouseListener(listner);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namebox = new javax.swing.JTextField();
        mnamebox = new javax.swing.JTextField();
        pricebox = new javax.swing.JTextField();
        modelbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wdatebox = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        ddatebox = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        savebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        nobox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1370, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namebox.setEditable(false);
        namebox.setBackground(new java.awt.Color(204, 204, 204));
        namebox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 156, 251, 30));

        mnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameboxActionPerformed(evt);
            }
        });
        getContentPane().add(mnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 250, 30));

        pricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceboxActionPerformed(evt);
            }
        });
        getContentPane().add(pricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 289, 250, 30));

        modelbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelboxActionPerformed(evt);
            }
        });
        getContentPane().add(modelbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 246, 250, 30));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("customer profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 527, 78));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Customer Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 31));

        idbox.setEditable(false);
        idbox.setBackground(new java.awt.Color(204, 204, 204));
        idbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });
        getContentPane().add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Machine Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 197, 131, 31));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Model");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 244, 131, 31));
        getContentPane().add(wdatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 368, 250, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 287, 124, 31));
        getContentPane().add(ddatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 330, 250, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Delivery Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 330, 119, 31));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Warranty Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 367, 133, 31));

        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 96, 200, 40));

        deletebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-recycle-bin-icon.png"))); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 330, 140, 38));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "File Number", "Customer Name"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 182, -1, 107));

        savebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save blue.png"))); // NOI18N
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 330, 128, 38));

        resetbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        resetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh blue.png"))); // NOI18N
        resetbtn.setText("RESET");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 330, 130, 38));

        searchbutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        searchbutton.setText("SEARCH");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 96, 107, 38));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "File No", "Customer Name", "Machine Name", "Model", "Price", "Delivery Date", "Warranty Date"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 434, 870, 120));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Serial NO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 31));

        nobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noboxActionPerformed(evt);
            }
        });
        getContentPane().add(nobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("File NO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, -60, 1960, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameboxActionPerformed

    private void priceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceboxActionPerformed

    private void modelboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelboxActionPerformed

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete?");

        if(x==0){

            String id1 = nobox.getText();

            try{
                String sql = "DELETE from customer_machine where id = ?";
                pst = conn.prepareStatement(sql);

                pst.setString(1, id1);

                pst.execute();

                //load table
                tableLoad();

                clearFields();

            }catch(SQLException e){
               
            }
        }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        String id= nobox.getText();
        String cid= idbox.getText();
        
        String cname= namebox.getText();
        String cmob1= mnamebox.getText();
        String cmob2= modelbox.getText();
        String companyname= pricebox.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ddate= sdf.format(ddatebox.getDate());
        String wdate= sdf.format(wdatebox.getDate());
       
        try{
            String q = "INSERT INTO customer_machine (id,cid,cname, mname, model, price, ddate, wdate) values (?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(q);
            pst.setString(1,cid);
            pst.setString(2,cid);
            pst.setString(3,cname);
            pst.setString(4,cmob1);
            pst.setString(5,cmob2);
            pst.setString(6,companyname);
            pst.setString(7,ddate);
            pst.setString(8,wdate);
            
            
            
                
        if(cid.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type a Customer ID");
        }else  if(cname.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Name");
        }else  if(cmob1.equals("")||cmob1.charAt(0)=='0' || cmob1.length()==10){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Mobile");
        }else  if(cmob2.equals("")||cmob2.charAt(0)=='0' || cmob2.length()==10){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Mobile2");
        }else  if(companyname.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Company Name");
        }else  if(ddate.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type machine deliver date");
        }else  if(wdate.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type warranty date");
        }
            
            
            
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Your Customer's New Machine Inserted Successfully!!");
            clearFields();
            tableLoad();

        } catch(SQLException e){
            
        }
       

    }//GEN-LAST:event_savebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_resetbtnActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
         String sname1 = searchbox.getText();

        try{
            String sql = "SELECT cid , cname FROM customer where cname LIKE '%"+sname1+"%'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            table2.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(SQLException e){

        }
        
         String sname = searchbox.getText();

        try{
            String sql = "SELECT id, cid, cname, mname, model, price, ddate, wdate FROM customer_machine where cname LIKE '%"+sname+"%'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(SQLException e){

        }

    }//GEN-LAST:event_searchbuttonActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
         int r = table2.getSelectedRow();
        String eid= table2.getValueAt(r, 0).toString();
       
        
        String cname = table2.getValueAt(r, 1).toString();
        
        

        idbox.setText(eid);
        namebox.setText(cname);
    }//GEN-LAST:event_table2MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here
        int r = table.getSelectedRow();
       
        String no = table.getValueAt(r, 0).toString();
        String id = table.getValueAt(r, 1).toString();
        String name = table.getValueAt(r, 2).toString();
        String machine = table.getValueAt(r, 3).toString();
        String model = table.getValueAt(r, 4).toString();
        String price = table.getValueAt(r, 5).toString();
        java.util.Date ddate = (java.util.Date)table.getValueAt(r, 6);
        java.util.Date wdate = (java.util.Date)table.getValueAt(r, 7);
        
            
            
       
        
        nobox.setText(no);
        idbox.setText(id);
        namebox.setText(name);
        mnamebox.setText(machine);
        modelbox.setText(model);
        pricebox.setText(price);
        ddatebox.setDate(ddate);
        wdatebox.setDate(wdate);
       
                             
    }//GEN-LAST:event_tableMouseClicked

    private void noboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ddatebox;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mnamebox;
    private javax.swing.JTextField modelbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField nobox;
    private javax.swing.JTextField pricebox;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private com.toedter.calendar.JDateChooser wdatebox;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        nobox.setText(null);
       idbox.setText(null);
       namebox.setText(null);
       mnamebox.setText(null);
       modelbox.setText(null);
       pricebox.setText(null);
       ddatebox.setDate(null); 
       wdatebox.setDate(null); 
       searchbox.setText(null);
    }

    private void tableLoad() {
         try{
            String sql="SELECT cid, cname, mname, model, price, ddate , wdate  FROM customer_machine";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(SQLException e){
            
        }
    }
}
