/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

/**
 *
 * @author Hp Pavilion
 */
public class MainHRInterface extends javax.swing.JFrame {

    /**
     * Creates new form newMainEmployeeMainInterface
     */
    public MainHRInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeebtn = new javax.swing.JButton();
        repairbtn = new javax.swing.JButton();
        black = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        restore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeebtn.setBackground(new java.awt.Color(204, 204, 255));
        employeebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        employeebtn.setForeground(new java.awt.Color(0, 51, 153));
        employeebtn.setText("employee management");
        employeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeebtnActionPerformed(evt);
            }
        });
        getContentPane().add(employeebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 49));

        repairbtn.setBackground(new java.awt.Color(204, 204, 255));
        repairbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        repairbtn.setForeground(new java.awt.Color(0, 0, 153));
        repairbtn.setText("salary maintenance");
        repairbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairbtnActionPerformed(evt);
            }
        });
        getContentPane().add(repairbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 49));

        black.setBackground(new java.awt.Color(204, 255, 255));
        black.setPreferredSize(new java.awt.Dimension(1371, 670));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coverrrrr.jpg"))); // NOI18N
        black.add(jLabel2);
        jLabel2.setBounds(-20, -10, 1410, 720);

        getContentPane().add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1380, 700));

        restore.setText("Exit");
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });
        getContentPane().add(restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 11, -1, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coverrrrr.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1470, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeebtnActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        NewemployeeDetails c=new NewemployeeDetails();
        black.add(c).setVisible(true);
    }//GEN-LAST:event_employeebtnActionPerformed

    private void repairbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairbtnActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        salary c=new salary();
        black.add(c).setVisible(true);

    }//GEN-LAST:event_repairbtnActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
        UserLogin admin = new UserLogin();
        admin.setVisible(true);
    }//GEN-LAST:event_restoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHRInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHRInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHRInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHRInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHRInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane black;
    private javax.swing.JButton employeebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton repairbtn;
    private javax.swing.JButton restore;
    // End of variables declaration//GEN-END:variables
}
