/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

import java.awt.Dimension;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;
import static riyoninternational.User_Management_1.x;


/**
 *
 * @author Hp Pavilion
 */
public class NewCustomers extends javax.swing.JInternalFrame {
    Connection conn=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    static String v;
    

    /**
     * Creates new form NewCustomers
     */
    public NewCustomers() {
        initComponents();
        conn = DBconnect.connect();
        
        tableLoad();
        
        v = "v";
        
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listner : basicInternalFrameUI.getNorthPane().getMouseListeners()){
            basicInternalFrameUI.getNorthPane().removeMouseListener(listner);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        machine1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mwd = new javax.swing.JTextField();
        mdd = new javax.swing.JTextField();
        mprice = new javax.swing.JTextField();
        mmodel = new javax.swing.JTextField();
        mcname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cdistrictbox = new javax.swing.JTextField();
        ccitybox = new javax.swing.JTextField();
        cemailbox = new javax.swing.JTextField();
        caddbox = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        ccommobbox = new javax.swing.JTextField();
        ccombox = new javax.swing.JTextField();
        cmob2box = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        cmob1box = new javax.swing.JTextField();
        cnamebox = new javax.swing.JTextField();
        jLabel208 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        csearchbox = new javax.swing.JTextField();
        jLabel217 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jLabel218 = new javax.swing.JLabel();
        cidbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Machine Name", "Model", "Price", "Delivery Date", "Warranty Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mwdActionPerformed(evt);
            }
        });

        mdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mddActionPerformed(evt);
            }
        });

        mprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpriceActionPerformed(evt);
            }
        });

        mmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmodelActionPerformed(evt);
            }
        });

        mcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcnameActionPerformed(evt);
            }
        });

        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel1.setText("MACHINE DETAILS");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        jButton6.setText("SAVE");

        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        jButton5.setText("RESET");

        jButton8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        jButton8.setText("DELETE");

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        jButton3.setText("UPDATE");

        jButton7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        jButton7.setText("PRINT");

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Machine Name", "Model", "Price", "Delivery Date", "Warranty Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Machine Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Model");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Price");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Delivery Date");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Warranty Date");

        javax.swing.GroupLayout machine1Layout = new javax.swing.GroupLayout(machine1.getContentPane());
        machine1.getContentPane().setLayout(machine1Layout);
        machine1Layout.setHorizontalGroup(
            machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(machine1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(machine1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mcname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(machine1Layout.createSequentialGroup()
                        .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mprice, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(971, Short.MAX_VALUE))
            .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(machine1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(mmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(570, 570, 570)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(930, 930, 930)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(690, 690, 690)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(710, 710, 710)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(mwd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(820, 820, 820)
                            .addComponent(jButton3))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(440, 440, 440)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(mdd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(920, 920, 920)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(machine1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        machine1Layout.setVerticalGroup(
            machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(machine1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(machine1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(mmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(334, 334, 334)
                            .addComponent(mwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(296, 296, 296)
                            .addComponent(mdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(machine1Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(machine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(machine1Layout.createSequentialGroup()
                    .addGap(0, 257, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(171, 171, 171)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 61, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1370, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cdistrictbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdistrictboxActionPerformed(evt);
            }
        });
        getContentPane().add(cdistrictbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 447, 250, 30));

        ccitybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccityboxActionPerformed(evt);
            }
        });
        getContentPane().add(ccitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 409, 250, 30));

        cemailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailboxActionPerformed(evt);
            }
        });
        getContentPane().add(cemailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 371, 250, 30));

        caddbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddboxActionPerformed(evt);
            }
        });
        getContentPane().add(caddbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 333, 250, 30));

        savebtn.setBackground(new java.awt.Color(51, 51, 51));
        savebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save blue.png"))); // NOI18N
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, 38));

        resetbtn.setBackground(new java.awt.Color(51, 51, 51));
        resetbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        resetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh blue.png"))); // NOI18N
        resetbtn.setText("RESET");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 140, 38));

        deletebtn.setBackground(new java.awt.Color(51, 51, 51));
        deletebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-recycle-bin-icon.png"))); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 140, 38));

        ccommobbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccommobboxActionPerformed(evt);
            }
        });
        getContentPane().add(ccommobbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 295, 250, 30));

        ccombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccomboxActionPerformed(evt);
            }
        });
        getContentPane().add(ccombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 257, 250, 30));

        cmob2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmob2boxActionPerformed(evt);
            }
        });
        getContentPane().add(cmob2box, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 219, 250, 30));

        updatebtn.setBackground(new java.awt.Color(51, 51, 51));
        updatebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Text-Edit-icon (1).png"))); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 140, 38));

        cmob1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmob1boxActionPerformed(evt);
            }
        });
        getContentPane().add(cmob1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 181, 250, 30));

        cnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameboxActionPerformed(evt);
            }
        });
        getContentPane().add(cnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 143, 250, 30));

        jLabel208.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel208.setText("CUSTOMER management");
        getContentPane().add(jLabel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 720, 78));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "File NO", "Name", "Mobile 01", "Mobile 02", "Company Name", "Company Mobile", "Address", "Email", "City", "District"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane22.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMaxWidth(100);
            table.getColumnModel().getColumn(9).setResizable(false);
        }

        getContentPane().add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 894, 200));

        csearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csearchboxActionPerformed(evt);
            }
        });
        getContentPane().add(csearchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 200, 40));

        jLabel217.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel217.setForeground(new java.awt.Color(153, 153, 153));
        jLabel217.setText("Customer Name");
        getContentPane().add(jLabel217, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 141, 145, 31));

        jLabel216.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel216.setForeground(new java.awt.Color(153, 153, 153));
        jLabel216.setText("Mobile 01");
        getContentPane().add(jLabel216, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 179, 145, 31));

        jLabel215.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel215.setForeground(new java.awt.Color(153, 153, 153));
        jLabel215.setText("Mobile 02");
        getContentPane().add(jLabel215, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 217, 145, 31));

        jLabel214.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel214.setForeground(new java.awt.Color(153, 153, 153));
        jLabel214.setText("Company Name");
        getContentPane().add(jLabel214, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 255, 145, 31));

        jLabel213.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel213.setForeground(new java.awt.Color(153, 153, 153));
        jLabel213.setText("Company Mobile");
        getContentPane().add(jLabel213, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 145, 31));

        jLabel212.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel212.setForeground(new java.awt.Color(153, 153, 153));
        jLabel212.setText("Address");
        getContentPane().add(jLabel212, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 145, 31));

        jLabel211.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel211.setForeground(new java.awt.Color(153, 153, 153));
        jLabel211.setText("Email");
        getContentPane().add(jLabel211, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 369, 145, 31));

        jLabel210.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel210.setForeground(new java.awt.Color(153, 153, 153));
        jLabel210.setText("City");
        getContentPane().add(jLabel210, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 407, 145, 31));

        jLabel209.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel209.setForeground(new java.awt.Color(153, 153, 153));
        jLabel209.setText("District");
        getContentPane().add(jLabel209, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 445, 145, 31));

        searchbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 17)); // NOI18N
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 90, 150, 38));

        jLabel218.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel218.setForeground(new java.awt.Color(153, 153, 153));
        jLabel218.setText("Customer ID");
        getContentPane().add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 103, 145, 31));

        cidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidboxActionPerformed(evt);
            }
        });
        getContentPane().add(cidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 105, 86, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdistrictboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdistrictboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdistrictboxActionPerformed

    private void ccityboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccityboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccityboxActionPerformed

    private void cemailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailboxActionPerformed

    private void caddboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddboxActionPerformed

    private void ccommobboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccommobboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccommobboxActionPerformed

    private void ccomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccomboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccomboxActionPerformed

    private void cmob2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmob2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmob2boxActionPerformed

    private void cmob1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmob1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmob1boxActionPerformed

    private void cnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameboxActionPerformed

    private void csearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csearchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csearchboxActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
         String cname1 = csearchbox.getText();

        try{
            String sql = "SELECT * FROM customer where cname LIKE '%"+cname1+"%'";


            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(SQLException e){
           
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        String cid= cidbox.getText();
        String cname= cnamebox.getText();
        String cmob1= cmob1box.getText();
        String cmob2= cmob2box.getText();
        String companyname= ccombox.getText();
        String companymob= ccommobbox.getText();
        String cadd= caddbox.getText();
        String cemail= cemailbox.getText();
        String city= ccitybox.getText();
        String district= cdistrictbox.getText();
        
            
        if(cid.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type a Customer ID");
        }else if(cname.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Name");
        }else  if(cmob1.equals("")|| cmob1.charAt(0)=='0' || cmob1.length()==10){
            
            JOptionPane.showMessageDialog(null, "Please type a valid Customer Mobile");
        }else  if(cmob2.equals("")|| cmob2.charAt(0)=='0' || cmob2.length()==10 ){
            
            JOptionPane.showMessageDialog(null, "Please type a valid Customer Mobile2");
        }else  if(companyname.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Company Name");
        }else  if(companymob.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer CompanyMobile");
        }else  if(cadd.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer address");
        }else  if(cemail.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Email");
        }else  if(city.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer City");
        }else  if(district.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer District");
        }
            
        
        
        try{
            String q = "INSERT INTO customer ( cid,cname, mobile01, mobile02, companyname, comMobile, address, email, city, district) values (?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(q);

            pst.setString(1,cid);
            pst.setString(2,cname);
            pst.setString(3,cmob1);
            pst.setString(4,cmob2);
            pst.setString(5,companyname);
            pst.setString(6,companymob);
            pst.setString(7,cadd);
            pst.setString(8,cemail);
            pst.setString(9,city);
            pst.setString(10,district);
            
            
        
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Your New Customer Inserted Successfully!!");
            clearFields();
            tableLoad();

        } catch(SQLException e){
            
        }
        
        
          
        
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete?");

        if(x==0){

            String cid = cidbox.getText();

            try{
                String sql = "DELETE from customer where cid = ?";
                pst = conn.prepareStatement(sql);

                pst.setString(1, cid);

                pst.execute();

                //load table
                tableLoad();

                clearFields();

            }catch(SQLException e){
               
            }
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update?");

        
        String cid= cidbox.getText();
        String name= cnamebox.getText();
        String mob1= cmob1box.getText();
        String mob2= cmob2box.getText();
        String companyname= ccombox.getText();
        String companyMob= ccommobbox.getText();
        String address= caddbox.getText();
        String email= cemailbox.getText();
        String city= ccitybox.getText();
        String district= cdistrictbox.getText();
      
            try {
                String sql = ("UPDATE customer SET cid ='"+cid+"',  cname = '"+name+"', mobile01 = '"+mob1+"', mobile02 = '"+mob2+"', companyname = '"+companyname+"', comMobile = '"+companyMob+"', address = '"+address+"', email = '"+email+"', city = '"+city+"', district = '"+district+"'  where cid ='"+cid+"' ");

                pst = conn.prepareStatement(sql);
    
                pst.execute();

                JOptionPane.showMessageDialog(null, "Updated Successfully!!");
               
                //load table
                tableLoad();
                clearFields();
                
                

            } catch (Exception ex) {
                 
            }
            
        
    
         
    }                                         

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
         
       
    }//GEN-LAST:event_updatebtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int r = table.getSelectedRow();
        String cid = table.getValueAt(r, 0).toString();
        String cname = table.getValueAt(r, 1).toString();
        String mobile1 = table.getValueAt(r, 2).toString();
        String mobile2 = table.getValueAt(r, 3).toString();
        String comname = table.getValueAt(r, 4).toString();
        String commobile = table.getValueAt(r, 5).toString();
        String address = table.getValueAt(r, 6).toString();
        String email = table.getValueAt(r, 7).toString();
        String city = table.getValueAt(r, 8).toString();
        String district= table.getValueAt(r, 9).toString();
        
        cidbox.setText(cid);
        cnamebox.setText(cname);
        cmob1box.setText(mobile1);
        cmob2box.setText(mobile2);
        ccombox.setText(comname);
        ccommobbox.setText(commobile);
        caddbox.setText(address);
        cemailbox.setText(email);
        ccitybox.setText(city);
        cdistrictbox.setText(district);
     
    }//GEN-LAST:event_tableMouseClicked

    private void cidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidboxActionPerformed

    private void mwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mwdActionPerformed

    private void mddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mddActionPerformed

    private void mpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpriceActionPerformed

    private void mmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmodelActionPerformed

    private void mcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcnameActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caddbox;
    private javax.swing.JTextField ccitybox;
    private javax.swing.JTextField ccombox;
    private javax.swing.JTextField ccommobbox;
    private javax.swing.JTextField cdistrictbox;
    private javax.swing.JTextField cemailbox;
    private javax.swing.JTextField cidbox;
    private javax.swing.JTextField cmob1box;
    private javax.swing.JTextField cmob2box;
    private javax.swing.JTextField cnamebox;
    private javax.swing.JTextField csearchbox;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JDialog machine1;
    private javax.swing.JTextField mcname;
    private javax.swing.JTextField mdd;
    private javax.swing.JTextField mmodel;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mprice;
    private javax.swing.JTextField mwd;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable table;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void tableLoad() {
          try{
            String sql="SELECT * FROM customer";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(SQLException e){
            
        }
    }

    private void clearFields() {
        cidbox.setText(null);
        cnamebox.setText(null);
        cmob1box.setText(null);
        cmob2box.setText(null);
        ccombox.setText(null);
        ccommobbox.setText(null);
        caddbox.setText(null);
        cemailbox.setText(null);
        ccitybox.setText(null);
        cdistrictbox.setText(null);
        csearchbox.setText(null);
    }
}
