/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hp Pavilion
 */
public class NewemployeeDetails extends javax.swing.JInternalFrame {
    
    Connection conn=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    

    /**
     * Creates new form NewemployeeDetails
     */
    public NewemployeeDetails() {
        initComponents();
        conn = DBconnect.connect();
        
        tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eidbox = new javax.swing.JTextField();
        enicbox = new javax.swing.JTextField();
        eaddressbox = new javax.swing.JTextField();
        emob3box = new javax.swing.JTextField();
        emob2box = new javax.swing.JTextField();
        emob1box = new javax.swing.JTextField();
        eemailbox = new javax.swing.JTextField();
        esearchbox = new javax.swing.JTextField();
        edeletebtn = new javax.swing.JButton();
        esavebtn = new javax.swing.JButton();
        esearchbtn = new javax.swing.JButton();
        eresetbtn = new javax.swing.JButton();
        eupdatebtn = new javax.swing.JButton();
        enamebox1 = new javax.swing.JTextField();
        enamebox2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edobbox = new com.toedter.calendar.JDateChooser();
        ejoineddatebox = new com.toedter.calendar.JDateChooser();
        eresignedbox = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1370, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel1.setText("Employee Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 549, 90));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Company Mobile  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Emergency Mobile  ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Address  ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Date of Resigned  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 180, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Employee ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Contact Mobile  ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Employee NIC      ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Date Of Birth   ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Email   ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setText("Date of Appointment  ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 180, 40));

        eidbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        eidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidboxActionPerformed(evt);
            }
        });
        getContentPane().add(eidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 80, 40));

        enicbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enicboxActionPerformed(evt);
            }
        });
        getContentPane().add(enicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 360, 40));

        eaddressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaddressboxActionPerformed(evt);
            }
        });
        getContentPane().add(eaddressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 360, 40));

        emob3box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emob3boxActionPerformed(evt);
            }
        });
        getContentPane().add(emob3box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 360, 40));

        emob2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emob2boxActionPerformed(evt);
            }
        });
        getContentPane().add(emob2box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 360, 40));

        emob1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emob1boxActionPerformed(evt);
            }
        });
        getContentPane().add(emob1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 360, 40));

        eemailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eemailboxActionPerformed(evt);
            }
        });
        getContentPane().add(eemailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 360, 40));

        esearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esearchboxActionPerformed(evt);
            }
        });
        esearchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                esearchboxKeyPressed(evt);
            }
        });
        getContentPane().add(esearchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 200, 40));

        edeletebtn.setBackground(new java.awt.Color(204, 255, 255));
        edeletebtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        edeletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-recycle-bin-icon.png"))); // NOI18N
        edeletebtn.setText("DELETE");
        edeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(edeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 300, 150, 50));

        esavebtn.setBackground(new java.awt.Color(204, 255, 255));
        esavebtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        esavebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save blue.png"))); // NOI18N
        esavebtn.setText("SAVE");
        esavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esavebtnActionPerformed(evt);
            }
        });
        getContentPane().add(esavebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 300, 150, 50));

        esearchbtn.setBackground(new java.awt.Color(204, 255, 255));
        esearchbtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        esearchbtn.setText("SEARCH");
        esearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(esearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 40, 130, 40));

        eresetbtn.setBackground(new java.awt.Color(204, 255, 255));
        eresetbtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        eresetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh blue.png"))); // NOI18N
        eresetbtn.setText("RESET");
        eresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eresetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eresetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 300, 150, 50));

        eupdatebtn.setBackground(new java.awt.Color(204, 255, 255));
        eupdatebtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        eupdatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Text-Edit-icon (1).png"))); // NOI18N
        eupdatebtn.setText("UPDATE");
        eupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eupdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(eupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1088, 300, 150, 50));

        enamebox1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        enamebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamebox1ActionPerformed(evt);
            }
        });
        getContentPane().add(enamebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 360, 40));

        enamebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamebox2ActionPerformed(evt);
            }
        });
        getContentPane().add(enamebox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 360, 40));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setText("Employee Name  ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 40));

        edobbox.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(edobbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 360, 40));

        ejoineddatebox.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(ejoineddatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 360, 40));

        eresignedbox.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(eresignedbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 360, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 730, 100));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidboxActionPerformed

    private void enicboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enicboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enicboxActionPerformed

    private void eaddressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaddressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaddressboxActionPerformed

    private void emob3boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emob3boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emob3boxActionPerformed

    private void emob2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emob2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emob2boxActionPerformed

    private void emob1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emob1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emob1boxActionPerformed

    private void eemailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eemailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eemailboxActionPerformed

    private void esearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esearchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esearchboxActionPerformed

    private void esearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esearchbtnActionPerformed
        // TODO add your handling code here:
          String ename1 = esearchbox.getText();

        try{
            String sql = "SELECT  eid,ename,edob,emobile,ecompanymobile,emergencymobile,address,email,joindate,resigndate FROM employee where ename LIKE '%"+ename1+"%'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(SQLException e){
           
        }
    }//GEN-LAST:event_esearchbtnActionPerformed
     
    private void esavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esavebtnActionPerformed
        // TODO add your handling code here:
       
        String eid= eidbox.getText();
        String ename= enamebox1.getText();
        String enic= enicbox.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String edob= sdf.format(edobbox.getDate());
        String emob1= emob1box.getText();
        String ecompanymob= emob2box.getText();
        String eemergencymob= emob3box.getText();
        String eaddress= eaddressbox.getText();
        String eemail= eemailbox.getText();
        String ejoindate= sdf.format(ejoineddatebox.getDate());
        String eresigndate= sdf.format(eresignedbox.getDate());
        
        try{
            String q = "INSERT INTO employee (eid,ename,enic,edob,emobile,ecompanymobile,emergencymobile,address,email,joindate,resigndate) values (?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(q);

           
            pst.setString(1,eid);
            pst.setString(2,ename);
            pst.setString(3,enic);
            pst.setString(4,edob);
            pst.setString(5,emob1);
            pst.setString(6,ecompanymob);
            pst.setString(7,eemergencymob);
            pst.setString(8,eaddress);
            pst.setString(9,eemail);
            pst.setString(10,ejoindate);
            pst.setString(11,eresigndate);
            
            if(eid.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type a Customer ID");
        }else  if(ename.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Name");
        }else  if(enic.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Mobile");
        }else  if(edob.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Mobile2");
        }else  if(emob1.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Company Name");
        }else  if(ecompanymob.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type machine deliver date");
        }else  if(eemergencymob.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type warranty date");
        }else  if(eaddress.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Mobile2");
        }else  if(eemail.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type Customer Company Name");
        }else  if(ejoindate.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type machine deliver date");
        }else  if(eresigndate.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type warranty date");
        }
          
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Your New Employee Inserted Successfully!!");
             clearFields();
            tableLoad();

        } catch(SQLException e){
            
        }
        
    }//GEN-LAST:event_esavebtnActionPerformed

    private void eresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eresetbtnActionPerformed
        // TODO add your handling code here:
        
        clearFields();
    }//GEN-LAST:event_eresetbtnActionPerformed

    private void enamebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enamebox1ActionPerformed

    private void enamebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enamebox2ActionPerformed

    private void edeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edeletebtnActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete?");

        if(x==0){

            String eid = eidbox.getText();

            try{
                String sql = "DELETE from employee where eid = ?";
                pst = conn.prepareStatement(sql);

                pst.setString(1, eid);

                pst.execute();

                //load table
                tableLoad();

                clearFields();

            }catch(SQLException e){
               
            }
        }
    }//GEN-LAST:event_edeletebtnActionPerformed

    private void eupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eupdatebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update?");
        String eid= eidbox.getText();
        String ename= enamebox1.getText();
        String enic= enicbox.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String edob= sdf.format(edobbox.getDate());
        String emob1= emob1box.getText();
        String ecompanymob= emob2box.getText();
        String eemergencymob= emob3box.getText();
        String eaddress= eaddressbox.getText();
        String eemail= eemailbox.getText();
        String ejoindate= sdf.format(ejoineddatebox.getDate());
        String eresigndate= sdf.format(eresignedbox.getDate());

        
        
            try {
                 String sql = ("UPDATE employee SET eid ='"+eid+"',  ename = '"+ename+"', enic = '"+enic+"', edob = '"+edob+"', emobile = '"+emob1+"', ecompanymobile = '"+ecompanymob+"', emergencymobile = '"+eemergencymob+"', address = '"+eaddress+"', email = '"+eemail+"', joindate = '"+ejoindate+"' , resigndate = '"+eresigndate+"' where eid ='"+eid+"' ");

                pst = conn.prepareStatement(sql);
    
                pst.execute();

                JOptionPane.showMessageDialog(null, "Updated Successfully!!");
               
                //load table
                tableLoad();
                clearFields();
                
                

            } catch (Exception ex) {
                 
            }
        
    }//GEN-LAST:event_eupdatebtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        
        int r = table.getSelectedRow();
       
        
        String e_id = table.getValueAt(r, 0).toString();
        String ename = table.getValueAt(r, 1).toString();
      
        java.util.Date dte = (java.util.Date)table.getValueAt(r, 2);
        String mob1 = table.getValueAt(r, 3).toString();
        String emob2 = table.getValueAt(r, 4).toString();
        String commob3 = table.getValueAt(r, 5).toString();
        String address = table.getValueAt(r, 6).toString();
        String email = table.getValueAt(r, 7).toString();
        java.util.Date jdte = (java.util.Date)table.getValueAt(r, 8);
        java.util.Date adte = (java.util.Date)table.getValueAt(r, 9);
        try{
            
            pst = conn.prepareStatement("select * from employee where eid = ?");
            pst.setString(1, e_id);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String nic_ = rs.getString("enic"); 
                enicbox.setText(nic_);
            }
            
            
        }catch(Exception e){
            
        }
        
        
      
        
        eidbox.setText(e_id);
        enamebox1.setText(ename);
      
        edobbox.setDate(dte);
        emob1box.setText(mob1);
        emob2box.setText(emob2);
        emob3box.setText(commob3);
         eaddressbox.setText(address);
        eemailbox.setText(email);
        ejoineddatebox.setDate(jdte);
        eresignedbox.setDate(adte);

       
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void esearchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esearchboxKeyPressed

    }//GEN-LAST:event_esearchboxKeyPressed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eaddressbox;
    private javax.swing.JButton edeletebtn;
    private com.toedter.calendar.JDateChooser edobbox;
    private javax.swing.JTextField eemailbox;
    private javax.swing.JTextField eidbox;
    private com.toedter.calendar.JDateChooser ejoineddatebox;
    private javax.swing.JTextField emob1box;
    private javax.swing.JTextField emob2box;
    private javax.swing.JTextField emob3box;
    private javax.swing.JTextField enamebox1;
    private javax.swing.JTextField enamebox2;
    private javax.swing.JTextField enicbox;
    private javax.swing.JButton eresetbtn;
    private com.toedter.calendar.JDateChooser eresignedbox;
    private javax.swing.JButton esavebtn;
    private javax.swing.JTextField esearchbox;
    private javax.swing.JButton esearchbtn;
    private javax.swing.JButton eupdatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
       
        eidbox.setText(null);
        enamebox1.setText(null);
        enicbox.setText(null);
        edobbox.setDate(null);
        emob1box.setText(null);
        emob2box.setText(null);
        emob3box.setText(null);
        eaddressbox.setText(null);
        eemailbox.setText(null);
        ejoineddatebox.setDate(null);
        eresignedbox.setDate(null);
    }

    private void tableLoad() {
        try{
            String sql="SELECT eid,ename,edob,emobile,ecompanymobile,emergencymobile,address,email,joindate,resigndate FROM employee";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(SQLException e){
            
        }
    }
}
