/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

/**
 *
 * @author Hp Pavilion
 */
public class newMainEmployeeMainInterface extends javax.swing.JFrame {

    /**
     * Creates new form newMainEmployeeMainInterface
     */
    public newMainEmployeeMainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerMangementbtn = new javax.swing.JButton();
        customerProfileBtn = new javax.swing.JButton();
        supliersdetails = new javax.swing.JButton();
        black = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        machinebtn1 = new javax.swing.JButton();
        restore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerMangementbtn.setBackground(new java.awt.Color(204, 204, 204));
        customerMangementbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        customerMangementbtn.setForeground(new java.awt.Color(0, 51, 153));
        customerMangementbtn.setText("customer management");
        customerMangementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMangementbtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerMangementbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, 49));

        customerProfileBtn.setBackground(new java.awt.Color(204, 204, 255));
        customerProfileBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        customerProfileBtn.setForeground(new java.awt.Color(0, 51, 153));
        customerProfileBtn.setText("customer profile");
        customerProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerProfileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 10, -1, 49));

        supliersdetails.setBackground(new java.awt.Color(204, 204, 255));
        supliersdetails.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        supliersdetails.setForeground(new java.awt.Color(0, 51, 153));
        supliersdetails.setText("SupPlier Details");
        supliersdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supliersdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(supliersdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 10, -1, 49));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/50-engineering-dna.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        black.add(jLabel2);
        jLabel2.setBounds(-310, 0, 1800, 700);

        jLabel4.setText("jLabel4");
        black.add(jLabel4);
        jLabel4.setBounds(1050, 100, 34, 14);

        getContentPane().add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 1370, 656));

        machinebtn1.setBackground(new java.awt.Color(204, 204, 255));
        machinebtn1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        machinebtn1.setForeground(new java.awt.Color(0, 51, 153));
        machinebtn1.setText("machine details");
        machinebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machinebtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(machinebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 10, -1, 49));

        restore.setText("Exit");
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });
        getContentPane().add(restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 11, -1, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coverrrrr.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1380, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerMangementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMangementbtnActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        NewCustomers c=new NewCustomers();
        black.add(c).setVisible(true);
    }//GEN-LAST:event_customerMangementbtnActionPerformed

    private void customerProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerProfileBtnActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        Customermachine c=new Customermachine();
        black.add(c).setVisible(true);

    }//GEN-LAST:event_customerProfileBtnActionPerformed

    private void supliersdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supliersdetailsActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        NewSupliers c=new NewSupliers();
        black.add(c).setVisible(true);

    }//GEN-LAST:event_supliersdetailsActionPerformed

    private void machinebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machinebtn1ActionPerformed
        // TODO add your handling code here:
        black.removeAll();
        NewMachineDetails c=new NewMachineDetails();
        black.add(c).setVisible(true);
    }//GEN-LAST:event_machinebtn1ActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
       UserLogin admin = new UserLogin();
       admin.setVisible(true);
    }//GEN-LAST:event_restoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newMainEmployeeMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newMainEmployeeMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newMainEmployeeMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newMainEmployeeMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newMainEmployeeMainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane black;
    private javax.swing.JButton customerMangementbtn;
    private javax.swing.JButton customerProfileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton machinebtn1;
    private javax.swing.JButton restore;
    private javax.swing.JButton supliersdetails;
    // End of variables declaration//GEN-END:variables
}
