/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riyoninternational;

import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hp Pavilion
 */
public class NewMachineDetails extends javax.swing.JInternalFrame {
    Connection conn=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form NewMachineDetails
     */
    public NewMachineDetails() {
        initComponents();
        conn = DBconnect.connect();
        
        tableLoad();
        
         BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listner : basicInternalFrameUI.getNorthPane().getMouseListeners()){
            basicInternalFrameUI.getNorthPane().removeMouseListener(listner);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        otherbox = new javax.swing.JTextField();
        Model = new javax.swing.JTextField();
        Mname = new javax.swing.JTextField();
        mprice = new javax.swing.JTextField();
        esavebtn = new javax.swing.JButton();
        eresetbtn = new javax.swing.JButton();
        edeletebtn = new javax.swing.JButton();
        eupdatebtn = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        esearchbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        MID = new javax.swing.JTextField();
        mcountry1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1370, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MACHINE Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 549, 80));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Machine ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 108, 150, 40));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setText("Machine Name  ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 158, 150, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Model Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 208, 150, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 258, 150, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Other Details");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 40));

        otherbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherboxActionPerformed(evt);
            }
        });
        getContentPane().add(otherbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 360, 80));

        Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelActionPerformed(evt);
            }
        });
        getContentPane().add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 208, 360, 40));

        Mname.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnameActionPerformed(evt);
            }
        });
        getContentPane().add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 158, 360, 40));

        mprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpriceActionPerformed(evt);
            }
        });
        getContentPane().add(mprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 260, 360, 40));

        esavebtn.setBackground(new java.awt.Color(204, 204, 255));
        esavebtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        esavebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save blue.png"))); // NOI18N
        esavebtn.setText("SAVE");
        esavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esavebtnActionPerformed(evt);
            }
        });
        getContentPane().add(esavebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 308, 130, 40));

        eresetbtn.setBackground(new java.awt.Color(204, 204, 255));
        eresetbtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        eresetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh blue.png"))); // NOI18N
        eresetbtn.setText("RESET");
        eresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eresetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eresetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 308, 130, 40));

        edeletebtn.setBackground(new java.awt.Color(204, 204, 255));
        edeletebtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        edeletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-recycle-bin-icon.png"))); // NOI18N
        edeletebtn.setText("DELETE");
        edeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(edeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 308, 145, 40));

        eupdatebtn.setBackground(new java.awt.Color(204, 204, 255));
        eupdatebtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        eupdatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Text-Edit-icon (1).png"))); // NOI18N
        eupdatebtn.setText("UPDATE");
        eupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eupdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(eupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1036, 308, -1, 40));

        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 200, 40));

        esearchbtn.setBackground(new java.awt.Color(204, 255, 255));
        esearchbtn.setFont(new java.awt.Font("Felix Titling", 1, 17)); // NOI18N
        esearchbtn.setText("SEARCH");
        esearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(esearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 130, 40));

        table.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Machine Name", "Model Number", "Price", "Country"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 770, 106));

        MID.setEditable(false);
        MID.setBackground(new java.awt.Color(204, 204, 204));
        MID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, 40));

        mcountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcountry1ActionPerformed(evt);
            }
        });
        getContentPane().add(mcountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 308, 360, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Country");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 308, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1540, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otherboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherboxActionPerformed

    private void ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelActionPerformed

    private void MnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnameActionPerformed

    private void mpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpriceActionPerformed

    private void esavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esavebtnActionPerformed
        // TODO add your handling code here:
        
        String name= Mname.getText();
        String model= Model.getText();
        String price= mprice.getText();
        String country= mcountry1.getText();
        String other= otherbox.getText();
        
        try{
            String q = "INSERT INTO machine ( name, modelNu, price, country, other) values (?,?,?,?,?)";
            pst = conn.prepareStatement(q);

            pst.setString(1,name);
            pst.setString(2,model);
            pst.setString(3,price);
            pst.setString(4,country);
            pst.setString(5,other);
      
                
        if(name.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type a Customer Name");
        }else  if(model.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type  model number");
        }else  if(price.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type machine price");
        }else  if(country.equals("")){
            
            JOptionPane.showMessageDialog(null, "Please type country");
        }else  if(other.equals(""))
            
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Your Machine Details Inserted Successfully!!");
            clearFields();
            tableLoad();

        } catch(SQLException e){
            
        }
        

       
    }                                       

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        

    }//GEN-LAST:event_esavebtnActionPerformed

    private void eresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eresetbtnActionPerformed
        // TODO add your handling code here:

        clearFields();
    }//GEN-LAST:event_eresetbtnActionPerformed

    private void edeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edeletebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete?");

        if(x==0){

            String mid = MID.getText();

            try{
                String sql = "DELETE from machine where id = ?";
                pst = conn.prepareStatement(sql);

                pst.setString(1, mid);

                pst.execute();

                //load table
                tableLoad();

                clearFields();

            }catch(SQLException e){

            }
        }
    }//GEN-LAST:event_edeletebtnActionPerformed

    private void eupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eupdatebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update?");

        if(x == 0){
            String mid= MID.getText();
            String mname=Mname.getText();
            String model=Model.getText();
            String price=mprice.getText();
            String country=mcountry1.getText();
            String other=otherbox.getText();
            
            

            try {
                String sql =("UPDATE machine SET id ='"+mid+"', name = '"+mname+"', modelNu = '"+model+"', price = '"+price+"', country = '"+country+"' , other = '"+other+"'  where id ='"+mid+"' ");


                pst = conn.prepareStatement(sql);

                pst.execute();

                JOptionPane.showMessageDialog(null, "Updated Successfully!!");
                clearFields();
                //load table
                tableLoad();

            } catch (SQLException ex) {
            }

        }
    }//GEN-LAST:event_eupdatebtnActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void esearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esearchbtnActionPerformed
        // TODO add your handling code here:
        String name1 = searchbox.getText();

        try{
            String sql = "SELECT * FROM machine where name LIKE '%"+name1+"%'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(SQLException e){

        }
    }//GEN-LAST:event_esearchbtnActionPerformed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMousePressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        int r = table.getSelectedRow();

        String e_id = table.getValueAt(r, 0).toString();
        String ename = table.getValueAt(r, 1).toString();
        String nic = table.getValueAt(r, 2).toString();
        String date = table.getValueAt(r,3).toString();
        String mob1 = table.getValueAt(r, 4).toString();
        String emob2 = table.getValueAt(r, 5).toString();
    

        MID.setText(e_id);
        Mname.setText(ename);
        Model.setText(nic);
        mprice.setText(date);
        mcountry1.setText(mob1);
        otherbox.setText(emob2);
        
       
        
    }//GEN-LAST:event_tableMouseClicked

    private void mcountry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcountry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcountry1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MID;
    private javax.swing.JTextField Mname;
    private javax.swing.JTextField Model;
    private javax.swing.JButton edeletebtn;
    private javax.swing.JButton eresetbtn;
    private javax.swing.JButton esavebtn;
    private javax.swing.JButton esearchbtn;
    private javax.swing.JButton eupdatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mcountry1;
    private javax.swing.JTextField mprice;
    private javax.swing.JTextField otherbox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

private void tableLoad() {
          try{
            String sql="SELECT * FROM machine";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(SQLException e){
            
        }
    }

    private void clearFields() {
        
        MID.setText(null);
        Mname.setText(null);
        Model.setText(null);
        mprice.setText(null);
        mcountry1.setText(null);
        otherbox.setText(null);
        searchbox.setText(null);
        
      
    }
}
